# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Expresso(object):
    def setupUi(self, Expresso):
        Expresso.setObjectName("Expresso")
        Expresso.resize(484, 339)
        self.centralwidget = QtWidgets.QWidget(Expresso)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.redact = QtWidgets.QPushButton(self.centralwidget)
        self.redact.setObjectName("redact")
        self.horizontalLayout_2.addWidget(self.redact)
        self.new_z = QtWidgets.QPushButton(self.centralwidget)
        self.new_z.setObjectName("new_z")
        self.horizontalLayout_2.addWidget(self.new_z)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        Expresso.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Expresso)
        self.statusbar.setObjectName("statusbar")
        Expresso.setStatusBar(self.statusbar)

        self.retranslateUi(Expresso)
        QtCore.QMetaObject.connectSlotsByName(Expresso)

    def retranslateUi(self, Expresso):
        _translate = QtCore.QCoreApplication.translate
        Expresso.setWindowTitle(_translate("Expresso", "MainWindow"))
        self.redact.setText(_translate("Expresso", "Редактировать"))
        self.new_z.setText(_translate("Expresso", "Добавить"))
